services:
  users:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/user-service
      PORT: 3000
    depends_on:
      db:
        condition: service_healthy

  balance:
    build:
      context: ./balance-service
      dockerfile: Dockerfile
    container_name: balance-service
    ports:
      - "3002:3002"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/balance-service
      RABBIT_URL: "amqp://rabbitmq"
      PORT: 3002
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  history:
    build:
      context: ./history-service
      dockerfile: Dockerfile
    container_name: history-service
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/history-service
      RABBIT_URL: "amqp://rabbitmq"
      PORT: 3001
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  db:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:4-management
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 30s
      retries: 10
